### ISSUE TITLE
Managed to integrating it. But is there a way to connect to the cloud and not local?

### ISSUE THREAD

**Issue by orenatan** [garbled1/balboa_homeassistan#14]
I managed adding it as well but only "local" which is not stable as the "cloud" and disconnects every minute.

Is there a way to connect to the "cloud connection" and not "local connection"?

**Comment by garbled1** [comment]
Sorry, there is no cloud support in this module.  I don't have any intention of changing that as I hate the cloud, but if someone else added it, I would not object.
However, I suspect it would not be compatible in any way with what this module does.  I think the API would be completely different, and would make far more sense to be a separate module entirely.
