### ISSUE TITLE
3 Pump Spa

### ISSUE THREAD

**Issue by stringy92** [garbled1/balboa_homeassistan#4]
As previously mentioned, the current software doesn't run the 3 pump spa very well I have noted down the actions of what happens when the pumps are triggered on HA

**Pump 1 -** 
Toggle On - Turns on Pump 1 with HA into Low mode
Toggle Off - HA turns on pump 2, however the Spa has turned Pump 1 into High. Turning off Pump 1 again on HA then turns off Pump 1

**Pump 2 -** 
Toggle On - Turns on Pump 2 & 3 on HA, however the spa has turned on Pump 2 in Low Mode
Toggle Off - Turns on Pump 2 into high mode, and unable to turn off this pump via HA in any combination 

**Pump 3 -** 
Toggle On - Turns on Pump 3 on HA, and then turns it off, however Pump 3 remains on in low mode on the spa
Toggle Off - Unable to toggle Off as when you toggle on, it immediately turns off

If I can offer any further help or support please let me know!

Thanks,

**Comment by garbled1** [comment]
Can you remind me what your spa configuration is?  which pumps are 2-speed, which ones are 1-speed?

**Comment by stringy92** [comment]
I have a 3 pump spa and they are all 2 speed. I also have a blower but unsure if this can be incorporated

**Comment by garbled1** [comment]
OK.. I somewhat understand this problem, and somewhat don't.  Let me explain.
I have a 2-pump 2-speed on both spa.  Ignoring pybalboa for a second, if I physically push buttons:

Start at all off
Push jet 1:  1 goes to low.
Push jet 1: 1 goes to high.
Push jet 1: 1 goes to off.  (good so far here)

Starting at all off:
Push jet 2: 2 goes low
Push jet 2: 2 goes high, 1 goes low.
Push jet 2: 2 goes off, 1 stays on low.  Spa won't let me stop 1 by pushing buttons.

Now the other issue is my number of pushes code was wrong, so I'm fixing that, that should solve the interaction problems, but if the spa is crazy, the spa is crazy.  :)  Will post more details as I go..

**Comment by stringy92** [comment]
Okay I understand your system better. The spa I have you are able to independently control each jet, however they do not control any of the other jets. However the button presses are the same as the above for low, high and off

**Comment by garbled1** [comment]
So I think I have this fixed.  I added a test to the main of the base pybalboa, that does a quick test of the spa buttons.. it's in master of pybalboa.  If you have a sec, could you stop homeassistant, and then try checking out master of pybalboa and running (from the git dir):

python3 pybalboa <ip of spa>

If you really wanted to get fancy, you could try editing the code at the bottom of pybalboa/__main__.py and changing the pump it pushes buttons for from 0 to 1 or 2.

**Comment by stringy92** [comment]
I will give this a go, but currently unable to get pybalboa to work on my Mac. I have dropped you a message on discord so we can chat further

**Comment by garbled1** [comment]
This should be fixed now, thank you!
