### ISSUE TITLE
what model WIFI module is this supporting

### ISSUE THREAD

**Issue by tonyfitzs** [garbled1/balboa_homeassistan#9]
Hi this isnt realy an issue per-sai I just want to confirm what model spar controler this supports. I curently have a Balboa Revolutioin which uses BWA (https://www.balboawatergroup.com/bwa) However this is the worlds worst spa controler application! and It looks likeI may have to upgrade due to an issue with my controler (main controler board has fried due to mousture). 

So I am looking at getting a controler that supports Control My Spa https://www.balboawatergroup.com/ControlMySpa. but I dont want to do that if this addon only supports BWA!... I am highly frustrated that it apearss that non of the spa manufacturers have the slightes clue about integration into anything like home automation.

**Comment by hgop67** [comment]
I have the ControlMySpa controller and this integration does not work with with my SPA. I would love to have the ControlMySpa intergrate with Hass but have found no solution. As there is a Google Assistant integration available I expect there is an API for interacting with ControlMySpa.

**Comment by tonyfitzs** [comment]
i was afraid of that. I have been in communication with Balboa to try and impress apon them that they are missing a potentialy huge opertunity for data collection. but like most near sighted manufactuers they dont see the importants. after all they make spas... I am working on atempting to build a more tightly coupled integration with a spa, basicaly im looking at building a device that connects to the spa using a Raspberry Pi running MQTT. if I can get the basics of the protocol to work on my Spa which is using the very crap BWA interface then it should be able to be modified to work with other models, this morning I came accross this thread on a different git hub page which you may find interesting as this applies to I belive your model controler. https://github.com/NickB1/OpenSpa/blob/master/documents/Balboa/Balboa_Display_Measurements.pdf

**Comment by garbled1** [comment]
This is for the BWA. Crap as it is, that's what I own.  :)
